spring.application.name=semi-mite-examples
mite.cache-dir=.mite-cache
mite.scripts-dir=cppScripts
mite.alignment-bytes=32


mite.compiler-flags[0]=-Ofast
mite.compiler-flags[1]=-march=native
mite.compiler-flags[2]=-mtune=native
mite.compiler-flags[3]=-flto=auto
mite.compiler-flags[4]=-funroll-loops
mite.compiler-flags[5]=-fomit-frame-pointer
mite.compiler-flags[6]=-ffast-math
mite.compiler-flags[7]=-funsafe-math-optimizations
mite.compiler-flags[8]=-fno-math-errno
mite.compiler-flags[9]=-fno-trapping-math
mite.compiler-flags[10]=-freciprocal-math

mite.compiler-flags[11]=-fpeel-loops
mite.compiler-flags[12]=-funswitch-loops
mite.compiler-flags[13]=-frename-registers



logging.level.org.example.parser=TRACE
logging.level.org.example.scanner=DEBUG
logging.level.org.example.compiler=DEBUG